name: HTML CI Pipeline
'on':
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: List Files
        run: ls -la
      - name: Print Success
        run: echo "CI Pipeline Executed Successfully!"
